### ISSUE TITLE
Fix python:latest-dev image

### ISSUE THREAD

**Issue by dlorenc** [chainguard-images/images#149]
### What software would you like us to add to our image catalog? (one per issue please)

The existing python image doesn't contain pip or a shell, making it hard to use as a build container. Ideally we should be able to model a Dockerfile like this:

```Dockerfile

FROM cgr.dev/chainguard/python-dev as builder
COPY . /app
RUN pip install -r requirements.txt

FROM cgr.dev/chainguard/python
COPY --from=builder /app /app
CMD ["python", "/app/main.py"]
```

Or something similar.

**Comment by tuananh** [comment]
pip is there. just need to add shell i guess.

![image](https://user-images.githubusercontent.com/627278/209461807-d82eff18-9ef1-40cc-a68e-eb61d5ea0c69.png)

**Comment by simon-sk** [comment]
@tuananh I ran your command: 
```
 docker run -it --rm --entrypoint pip cgr.dev/chainguard/python --version
```
but got the following error indicating that pip is not installed:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==22.3.1', 'console_scripts', 'pip')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pip", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pip
```

**Comment by tuananh** [comment]
@simon-sk lol i seriously dont know why. as you can see from the screenshot.

**Comment by simon-sk** [comment]
@tuananh I suspect that you might've had an older version of the image before that still had pip installed?

**Comment by patflynn** [comment]
@amouat to prioritise

**Comment by nikaro** [comment]
The `cgr.dev/chainguard/python:latest-dev` does have a shell, but not pip:

```
> docker run -it --rm cgr.dev/chainguard/python:latest-dev sh
/ $ python -m pip
/usr/bin/python: No module named pip
/ $ pip
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==22.3.1', 'console_scripts', 'pip')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pip", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pip
```

**Comment by amouat** [comment]
Yeah, there's something broken in the pip3 package. Let's get this fixed.

**Comment by patflynn** [comment]
I think @kaniini mentioned this may be fixed by a build that was happening today.

**Comment by patflynn** [comment]
related https://github.com/chainguard-images/images/issues/241

**Comment by patflynn** [comment]
should be fixed in our latest build.
