### ISSUE TITLE
[jdk] exception when run spring boot app in docker by using openjdk-jre-17

### ISSUE THREAD

**Issue by huseyin-tumer** [chainguard-images/images#230]
Hello!
I have spring boot application and using cgr.dev/chainguard/jdk:openjdk-jre-17 in dockerfile.
I get some timeout exceptions about couchbase on docker compose when i use image which is generated with cgr.dev/chainguard/jdk:openjdk-jre-17

exception:
`{"time": "2023-01-19T18:44:38.533", "level": "ERROR", "agent-name": "", "owner-id": "", "correlation-id": "", "request-path": "", "user-agent": "", "origin": "", "executor-user": "", "remote-host": "", "source": "org.springframework.boot.SpringApplication:835", "message": "Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'forbiddenWordsService': Invocation of init method failed; nested exception is com.couchbase.client.core.error.UnambiguousTimeoutException: GetRequest, Reason: TIMEOUT {\"cancelled\":true,\"completed\":true,\"coreId\":\"0x67e11a2e00000001\",\"idempotent\":true,\"reason\":\"TIMEOUT\",\"requestId\":2,\"requestType\":\"GetRequest\",\"retried\":127,\"retryReasons\":[\"BUCKET_OPEN_IN_PROGRESS\"],\"service\":{\"bucket\":\"SellerQA\",\"collection\":\"_default\",\"documentId\":\"FORBIDDEN_WORD\",\"opaque\":\"0x1\",\"scope\":\"_default\",\"type\":\"kv\",\"vbucket\":0},\"timeoutMs\":60000,\"timings\":{\"totalMicros\":60005068}} at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.22.jar!/:5.3.22] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.22.jar!/:5.3.22] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.22.jar!/:5.3.22] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.22.jar!/:5.3.22] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.22.jar!/:5.3.22] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.22.jar!/:5.3.22] Caused by: com.couchbase.client.core.error.UnambiguousTimeoutException: GetRequest, Reason: TIMEOUT {\"cancelled\":true,\"completed\":true,\"coreId\":\"0x67e11a2e00000001\",\"idempotent\":true,\"reason\":\"TIMEOUT\",\"requestId\":2,\"requestType\":\"GetRequest\",\"retried\":127,\"retryReasons\":[\"BUCKET_OPEN_IN_PROGRESS\"],\"service\":{\"bucket\":\"SellerQA\",\"collection\":\"_default\",\"documentId\":\"FORBIDDEN_WORD\",\"opaque\":\"0x1\",\"scope\":\"_default\",\"type\":\"kv\",\"vbucket\":0},\"timeoutMs\":60000,\"timings\":{\"totalMicros\":60005068}} at com.couchbase.client.core.msg.BaseRequest.cancel(BaseRequest.java:184) ~[core-io-2.2.7.jar!/:na] at com.couchbase.client.core.msg.Request.cancel(Request.java:70) ~[core-io-2.2.7.jar!/:na] at com.couchbase.client.core.Timer.lambda$register$2(Timer.java:157) ~[core-io-2.2.7.jar!/:na] at com.couchbase.client.core.deps.io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715) ~[core-io-2.2.7.jar!/:na] at com.couchbase.client.core.deps.io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34) ~[core-io-2.2.7.jar!/:na] at com.couchbase.client.core.deps.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703) ~[core-io-2.2.7.jar!/:na] Suppressed: java.lang.Exception: #block terminated with an error at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.22.jar!/:3.4.22] at reactor.core.publisher.Mono.block(Mono.java:1707) ~[reactor-core-3.4.22.jar!/:3.4.22] at org.springframework.data.couchbase.core.ExecutableFindByIdOperationSupport$ExecutableFindByIdSupport.one(ExecutableFindByIdOperationSupport.java:67) ~[spring-data-couchbase-4.3.6.jar!/:4.3.6] at org.springframework.data.couchbase.repository.support.SimpleCouchbaseRepository.findById(SimpleCouchbaseRepository.java:108) ~[spring-data-couchbase-4.3.6.jar!/:4.3.6] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na] "}`

Could you please help me!

**Comment by patflynn** [comment]
Hi there @huseyin-tumer. Do you have an example project we can reproduce from?   Is the couchbase job running in a separate container?   If you switch to using eclipse-temurin:17-jre-alpine as the base does the issue go away?

**Comment by patflynn** [comment]
closing due to inactivity.
