### ISSUE TITLE
[Bug][python:latest-dev] pip doesn't work properly on glibc based images

### ISSUE THREAD

**Issue by LoicSikidi** [chainguard-images/images#241]
Hi,

It seems that `pip` doesn't work properly in ***dev-XXX*** (glibc) images. Therefore, I can't build python application via `pip install`.

Please see the error below ⬇️ 

## Steps to reproduce

```bash
docker run -it --rm cgr.dev/chainguard/python:latest-dev@sha256:98828dffd6c8acbb971f7ddca0ed68954a3fdd892b6aa649fb69c9b3b7ac4ce2 pip --version

# Output ⬇️ 
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==22.3.1', 'console_scripts', 'pip')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/pip", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pip
```

**info**: `latest-musl-dev` works perfectly on the other hand. 

## Second feedback

It seems that [python images](https://github.com/chainguard-images/images/tree/main/images/python) don't have *smoke tests*.

Thank you in advance for your support 🙏

**Comment by dlorenc** [comment]
Hmm - it works now. I just tried:

```shell
% docker run --platform=linux/amd64 -it --rm cgr.dev/chainguard/python:latest-dev pip --version
Unable to find image 'cgr.dev/chainguard/python:latest-dev' locally
latest-dev: Pulling from chainguard/python
6dad41c098e8: Pull complete
Digest: sha256:becdce6d854a972e3b3cd605cddac5c2f01c549f559e36bf65a201dbbb77b08a
Status: Downloaded newer image for cgr.dev/chainguard/python:latest-dev
pip 22.3.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)
```

Could you confirm if it still is happening?

**Comment by LoicSikidi** [comment]
Indeed, it’s working now!

I’m closing the issue.

Thx again!
