### ISSUE TITLE
Superset - Missing static files

### ISSUE THREAD

**Issue by acherubinoklaviyo** [chainguard-images/images#2663]
### Which image/versions are related to this issue/feature request?

Superset v4.0.0

### Issue/Feature description

I am able to launch Superset and access it at `http://localhost:8088/` by following the provided instructions, but the WebUI does not appear to be correctly rendering and is unusable after logging in.

Below are comparison screenshots of both the login screen and the home screen directly after logging in. The first image in each comparison is from the Chainguard Superset image v4.0.0 and the second is from the base Apache Superset image v3.1.3.

### Login Page
![Chainguard Image v4.0.0](https://github.com/chainguard-images/images/assets/140840987/8d1ac294-91f8-4e20-a550-0fced4457863)

![Apache Image v3.1.3](https://github.com/chainguard-images/images/assets/140840987/88a3259c-1f57-4431-b036-1478fd4e4666)

### Home Page
![Chainguard Image v4.0.0](https://github.com/chainguard-images/images/assets/140840987/df147cb2-3c37-44d0-8a91-de371a0ff070)

![Apache Image v3.1.3](https://github.com/chainguard-images/images/assets/140840987/95209868-22f3-4887-8be5-c1418b25351d)

The differences here should be clear to see, with the logo in the top left corner notably missing on the login page and the homepage missing all content. The `X` and `Close` buttons do not do anything when clicked. This same behavior occurs weather the image is deployed with helm as described in the instructions or run directly as a docker container. I have tried deleting and re-pulling the image again but the same behavior is observed.

Looking at the log of the running container, it appears to repeat the following warnings whenever the page is loaded:

> 2024-05-10 17:15:17 192.168.65.1 - - [10/May/2024:21:15:17 +0000] "GET /superset/welcome/ HTTP/1.1" 200 49474 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
> 2024-05-10 17:15:17 HTTPException
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.dispatch_request()
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
> 2024-05-10 17:15:17     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 713, in <lambda>
> 2024-05-10 17:15:17     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
> 2024-05-10 17:15:17                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/scaffold.py", line 331, in send_static_file
> 2024-05-10 17:15:17     return send_from_directory(
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 590, in send_from_directory
> 2024-05-10 17:15:17     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
> 2024-05-10 17:15:17     raise NotFound()
> 2024-05-10 17:15:17 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 2024-05-10 17:15:17 2024-05-10 21:15:17,396:WARNING:superset.views.base:HTTPException
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.dispatch_request()
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
> 2024-05-10 17:15:17     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 713, in <lambda>
> 2024-05-10 17:15:17     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
> 2024-05-10 17:15:17                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/scaffold.py", line 331, in send_static_file
> 2024-05-10 17:15:17     return send_from_directory(
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 590, in send_from_directory
> 2024-05-10 17:15:17     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
> 2024-05-10 17:15:17     raise NotFound()
> 2024-05-10 17:15:17 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 2024-05-10 17:15:17 Exception on /static/assets/images/loading.gif [GET]
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.dispatch_request()
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
> 2024-05-10 17:15:17     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 713, in <lambda>
> 2024-05-10 17:15:17     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
> 2024-05-10 17:15:17                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/scaffold.py", line 331, in send_static_file
> 2024-05-10 17:15:17     return send_from_directory(
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 590, in send_from_directory
> 2024-05-10 17:15:17     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
> 2024-05-10 17:15:17     raise NotFound()
> 2024-05-10 17:15:17 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 2024-05-10 17:15:17 
> 2024-05-10 17:15:17 During handling of the above exception, another exception occurred:
> 2024-05-10 17:15:17 
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
> 2024-05-10 17:15:17     response = self.full_dispatch_request()
> 2024-05-10 17:15:17                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.handle_user_exception(e)
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
> 2024-05-10 17:15:17     return self.handle_http_exception(e)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
> 2024-05-10 17:15:17     return self.ensure_sync(handler)(e)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/superset/views/base.py", line 475, in show_http_exception
> 2024-05-10 17:15:17     return send_file(path, max_age=0), ex.code
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 537, in send_file
> 2024-05-10 17:15:17     return werkzeug.utils.send_file(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 427, in send_file
> 2024-05-10 17:15:17     stat = os.stat(path)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^
> 2024-05-10 17:15:17 FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/superset/venv/lib/python3.11/site-packages/superset/static/assets/404.html'
> 2024-05-10 17:15:17 2024-05-10 21:15:17,397:ERROR:superset.app:Exception on /static/assets/images/loading.gif [GET]
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.dispatch_request()
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
> 2024-05-10 17:15:17     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 713, in <lambda>
> 2024-05-10 17:15:17     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
> 2024-05-10 17:15:17                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/scaffold.py", line 331, in send_static_file
> 2024-05-10 17:15:17     return send_from_directory(
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 590, in send_from_directory
> 2024-05-10 17:15:17     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
> 2024-05-10 17:15:17     raise NotFound()
> 2024-05-10 17:15:17 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 2024-05-10 17:15:17 
> 2024-05-10 17:15:17 During handling of the above exception, another exception occurred:
> 2024-05-10 17:15:17 
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
> 2024-05-10 17:15:17     response = self.full_dispatch_request()
> 2024-05-10 17:15:17                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.handle_user_exception(e)
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
> 2024-05-10 17:15:17     return self.handle_http_exception(e)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
> 2024-05-10 17:15:17     return self.ensure_sync(handler)(e)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/superset/views/base.py", line 475, in show_http_exception
> 2024-05-10 17:15:17     return send_file(path, max_age=0), ex.code
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 537, in send_file
> 2024-05-10 17:15:17     return werkzeug.utils.send_file(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 427, in send_file
> 2024-05-10 17:15:17     stat = os.stat(path)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^
> 2024-05-10 17:15:17 FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/superset/venv/lib/python3.11/site-packages/superset/static/assets/404.html'
> 2024-05-10 17:15:17 192.168.65.1 - - [10/May/2024:21:15:17 +0000] "GET /static/assets/images/loading.gif HTTP/1.1" 500 332 "http://localhost:8088/superset/welcome/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
> 2024-05-10 17:15:17 HTTPException
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.dispatch_request()
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
> 2024-05-10 17:15:17     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 713, in <lambda>
> 2024-05-10 17:15:17     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
> 2024-05-10 17:15:17                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/scaffold.py", line 331, in send_static_file
> 2024-05-10 17:15:17     return send_from_directory(
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 590, in send_from_directory
> 2024-05-10 17:15:17     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
> 2024-05-10 17:15:17     raise NotFound()
> 2024-05-10 17:15:17 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 2024-05-10 17:15:17 2024-05-10 21:15:17,471:WARNING:superset.views.base:HTTPException
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.dispatch_request()
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
> 2024-05-10 17:15:17     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 713, in <lambda>
> 2024-05-10 17:15:17     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
> 2024-05-10 17:15:17                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/scaffold.py", line 331, in send_static_file
> 2024-05-10 17:15:17     return send_from_directory(
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 590, in send_from_directory
> 2024-05-10 17:15:17     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
> 2024-05-10 17:15:17     raise NotFound()
> 2024-05-10 17:15:17 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 2024-05-10 17:15:17 Exception on /static/assets/images/favicon.png [GET]
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.dispatch_request()
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
> 2024-05-10 17:15:17     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 713, in <lambda>
> 2024-05-10 17:15:17     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
> 2024-05-10 17:15:17                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/scaffold.py", line 331, in send_static_file
> 2024-05-10 17:15:17     return send_from_directory(
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 590, in send_from_directory
> 2024-05-10 17:15:17     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
> 2024-05-10 17:15:17     raise NotFound()
> 2024-05-10 17:15:17 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 2024-05-10 17:15:17 
> 2024-05-10 17:15:17 During handling of the above exception, another exception occurred:
> 2024-05-10 17:15:17 
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
> 2024-05-10 17:15:17     response = self.full_dispatch_request()
> 2024-05-10 17:15:17                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.handle_user_exception(e)
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
> 2024-05-10 17:15:17     return self.handle_http_exception(e)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
> 2024-05-10 17:15:17     return self.ensure_sync(handler)(e)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/superset/views/base.py", line 475, in show_http_exception
> 2024-05-10 17:15:17     return send_file(path, max_age=0), ex.code
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 537, in send_file
> 2024-05-10 17:15:17     return werkzeug.utils.send_file(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 427, in send_file
> 2024-05-10 17:15:17     stat = os.stat(path)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^
> 2024-05-10 17:15:17 FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/superset/venv/lib/python3.11/site-packages/superset/static/assets/404.html'
> 2024-05-10 17:15:17 2024-05-10 21:15:17,471:ERROR:superset.app:Exception on /static/assets/images/favicon.png [GET]
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.dispatch_request()
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
> 2024-05-10 17:15:17     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 713, in <lambda>
> 2024-05-10 17:15:17     view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
> 2024-05-10 17:15:17                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/scaffold.py", line 331, in send_static_file
> 2024-05-10 17:15:17     return send_from_directory(
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 590, in send_from_directory
> 2024-05-10 17:15:17     return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory
> 2024-05-10 17:15:17     raise NotFound()
> 2024-05-10 17:15:17 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 2024-05-10 17:15:17 
> 2024-05-10 17:15:17 During handling of the above exception, another exception occurred:
> 2024-05-10 17:15:17 
> 2024-05-10 17:15:17 Traceback (most recent call last):
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
> 2024-05-10 17:15:17     response = self.full_dispatch_request()
> 2024-05-10 17:15:17                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
> 2024-05-10 17:15:17     rv = self.handle_user_exception(e)
> 2024-05-10 17:15:17          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1669, in handle_user_exception
> 2024-05-10 17:15:17     return self.handle_http_exception(e)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/app.py", line 1609, in handle_http_exception
> 2024-05-10 17:15:17     return self.ensure_sync(handler)(e)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/superset/views/base.py", line 475, in show_http_exception
> 2024-05-10 17:15:17     return send_file(path, max_age=0), ex.code
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/flask/helpers.py", line 537, in send_file
> 2024-05-10 17:15:17     return werkzeug.utils.send_file(  # type: ignore[return-value]
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2024-05-10 17:15:17   File "/usr/share/superset/venv/lib/python3.11/site-packages/werkzeug/utils.py", line 427, in send_file
> 2024-05-10 17:15:17     stat = os.stat(path)
> 2024-05-10 17:15:17            ^^^^^^^^^^^^^
> 2024-05-10 17:15:17 FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/superset/venv/lib/python3.11/site-packages/superset/static/assets/404.html'
> 2024-05-10 17:15:17 192.168.65.1 - - [10/May/2024:21:15:17 +0000] "GET /static/assets/images/favicon.png HTTP/1.1" 500 332 "http://localhost:8088/superset/welcome/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

Please let me know if there is any further information I can provide to help in determining the cause of this.

**Comment by emosonic** [comment]
Has there been a solution?
