### ISSUE TITLE
`aws-cli`: `dateutil` <> `Python` version mismatch resulting syntax error

### ISSUE THREAD

**Issue by Dentrax** [chainguard-images/images#632]
Building the following `apko.yaml` resulting in a dependency issue related with `botocore` or `dateutil`:

```
contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - aws-cli

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

entrypoint:
  command: aws

archs:
- x86_64
- aarch64
```

Traceback:
```
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3.11/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/lib/python3.11/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/usr/lib/python3.11/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/usr/lib/python3.11/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/usr/lib/python3.11/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/usr/lib/python3.11/site-packages/botocore/docs/service.py", line 13, in <module>
    from botocore.docs.bcdoc.restdoc import DocumentStructure
  File "/usr/lib/python3.11/site-packages/botocore/docs/bcdoc/restdoc.py", line 17, in <module>
    from botocore.compat import OrderedDict
  File "/usr/lib/python3.11/site-packages/botocore/compat.py", line 31, in <module>
    from dateutil.tz import tzlocal
  File "/usr/lib/python3.11/site-packages/dateutil/__init__.py", line 3, in <module>
    from ._version import version as __version__
  File "/usr/lib/python3.11/site-packages/dateutil/_version.py", line 3
    version_tuple = (2\,8\,2)
                       ^
SyntaxError: unexpected character after line continuation character
```

I have also tested by including all the dependencies [here](https://github.com/wolfi-dev/os/blob/86c4e5e675553bf36b07610432aa28685112a0c1/aws-cli.yaml#L10-L19), but no luck. I think this is because of version mismatch between the `dateutil` module and the `Python` version I'm using. Any thoughts?

**Comment by imjasonh** [comment]
@kaniini do you understand what's going wrong here? Is it selecting the wrong Python?

**Comment by kaniini** [comment]
dateutil sources appear to be broken.

**Comment by Dentrax** [comment]
> dateutil sources appear to be broken.

Do you mean dateutil source is broken on the upstream repo or it's broken on wolfi/os py3-dateutil?
